### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by Silex** [reyzzz/quasaScale#2]
@reyzzz In order to make a Dockerfile for this repo, I need some build steps.

When I try to do the obvious, there are issues, for example, `bun run quasar build` (or `bun run build`) builds everything but then waits infinitly at the end of the process, I need to press CTRL-C. Any idea why this happens?

**Comment by reyzzz** [comment]
This project does not use bun but nodejs.
Before building the project you need to install the dependencies using the command `yarn`
The build should be done either using `npx quasar b` or if you install quasar globally you could directly do `quasar b`

**Comment by reyzzz** [comment]
Actually I am thinking of either getting a domain and hosting the frontend and make it available for everyone or to contact headscale devs, maybe they would host quasaScale on a subdomain of headscale, because there is no need that each user deploys quasaScale on his own.

**Comment by Silex** [comment]
Oh, I get it now. You use bun for the backend but nodejs for the frontend. Ok this should be easy to make the Dockerfile now.

**Comment by Silex** [comment]
Continuing in #3
