### ISSUE TITLE
Support browser refresh

### ISSUE THREAD

**Issue by Silex** [reyzzz/quasaScale#6]
Whenever I press CTRL+R or f5 by habit I get a 404 because /nodes or /acl is not a real path.

You'd probably use fragments URLs (like https://foo.com/#nodes).

**Comment by Silex** [comment]
@reyzzz told me to check "traefik SPA", will check next week

**Comment by reyzzz** [comment]
I have seen that you are using nginx in docker, I will put an example configuration for nginx in the PR

**Comment by Silex** [comment]
Done in the PR, just need to setup CI
