### ISSUE TITLE
Add helpers to copy ip/hostname/etc

### ISSUE THREAD

**Issue by Silex** [reyzzz/quasaScale#7]
![image](https://github.com/user-attachments/assets/542a9faf-0650-493e-aae8-ca8b4c067e0b)

Very logical to have them when you manage lots of devices and want to connect quickly :-)

**Comment by reyzzz** [comment]
Done

**Comment by Silex** [comment]
@reyzzz: most of your recent changes are not visible when using the mobile interface (copy ip, filter by online, etc)
